image:
  file: .gitpod.Dockerfile
tasks:
  - name: Clippy
    init: cargo clippy --all  -- -D warnings
  - name: Testing
    init: cargo test --all -v
  - name: Build
    init: cargo build

github:
  prebuilds:
    branches: true
    pullRequestsFromForks: true
    addLabel: prebuilt-in-gitpod
vscode:
  extensions:
    - hbenl.vscode-test-explorer@2.15.0:koqDUMWDPJzELp/hdS/lWw==
    - Swellaby.vscode-rust-test-adapter@0.11.0:Xg+YeZZQiVpVUsIkH+uiiw==
    - serayuzgur.crates@0.4.7:HMkoguLcXp9M3ud7ac3eIw==
    - belfz.search-crates-io@1.2.1:kSLnyrOhXtYPjQpKnMr4eQ==
    - bungcip.better-toml@0.3.2:3QfgGxxYtGHfJKQU7H0nEw==
    - webfreak.debug@0.24.0:1zVcRsAhewYEX3/A9xjMNw==
