[tasks.baseline]
command = "cargo"
args = ["build"]

[tasks.run]
command = "cargo"
args = ["run"]
dependencies = ["baseline"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["baseline"]

[tasks.check]
command = "cargo"
args = ["check"]
dependencies = ["baseline"]
